/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as analytics from "../analytics.js";
import type * as analytics_analyticsConstants from "../analytics/analyticsConstants.js";
import type * as analytics_utils_analyticsQueryRange from "../analytics/utils/analyticsQueryRange.js";
import type * as analytics_utils_buildAnalyticsRows from "../analytics/utils/buildAnalyticsRows.js";
import type * as analytics_utils_buildUserAnalyticsChartData from "../analytics/utils/buildUserAnalyticsChartData.js";
import type * as analytics_utils_comparedMetricUtils from "../analytics/utils/comparedMetricUtils.js";
import type * as analytics_utils_getAnalyticsMetricValue from "../analytics/utils/getAnalyticsMetricValue.js";
import type * as analytics_utils_sortAnalyticsItemsByMetric from "../analytics/utils/sortAnalyticsItemsByMetric.js";
import type * as auth_assertTrustedServer from "../auth/assertTrustedServer.js";
import type * as auth_auth from "../auth/auth.js";
import type * as auth_authRoutes from "../auth/authRoutes.js";
import type * as auth_convexCreateAuthRateLimitHook from "../auth/convexCreateAuthRateLimitHook.js";
import type * as auth_emails_sendVerificationOTP from "../auth/emails/sendVerificationOTP.js";
import type * as auth_guestConvexAuth from "../auth/guestConvexAuth.js";
import type * as auth_helpers_getAuthUserId from "../auth/helpers/getAuthUserId.js";
import type * as auth_helpers_isAdminUser from "../auth/helpers/isAdminUser.js";
import type * as auth_middleware_authMiddleware from "../auth/middleware/authMiddleware.js";
import type * as auth_queries_authQueries from "../auth/queries/authQueries.js";
import type * as auth_types_types from "../auth/types/types.js";
import type * as auth_utils_getEmailFromAuthBody from "../auth/utils/getEmailFromAuthBody.js";
import type * as convexRateLimiter from "../convexRateLimiter.js";
import type * as crons from "../crons.js";
import type * as email_templates_baseEmailTemplate from "../email/templates/baseEmailTemplate.js";
import type * as email_templates_emailFooterTemplate from "../email/templates/emailFooterTemplate.js";
import type * as email_templates_emailHeaderTemplate from "../email/templates/emailHeaderTemplate.js";
import type * as email_utils_convexEmailUtils from "../email/utils/convexEmailUtils.js";
import type * as helpers_convexGetRateLimitedUserId from "../helpers/convexGetRateLimitedUserId.js";
import type * as helpers_counterKeys from "../helpers/counterKeys.js";
import type * as helpers_createDeleteMutation from "../helpers/createDeleteMutation.js";
import type * as helpers_createProjection from "../helpers/createProjection.js";
import type * as helpers_fetchOptimized_createSearchQuery from "../helpers/fetchOptimized/createSearchQuery.js";
import type * as helpers_fetchOptimized_fetchOptimized from "../helpers/fetchOptimized/fetchOptimized.js";
import type * as helpers_fetchOptimized_index from "../helpers/fetchOptimized/index.js";
import type * as helpers_fetchOptimized_kit from "../helpers/fetchOptimized/kit.js";
import type * as helpers_fetchOptimized_types from "../helpers/fetchOptimized/types.js";
import type * as helpers_ownerCounterHelpers from "../helpers/ownerCounterHelpers.js";
import type * as helpers_paginationHelpers from "../helpers/paginationHelpers.js";
import type * as helpers_resolveUploadedImages from "../helpers/resolveUploadedImages.js";
import type * as helpers_uniqueIds from "../helpers/uniqueIds.js";
import type * as http from "../http.js";
import type * as migrations_backfillCountersInternal from "../migrations/backfillCountersInternal.js";
import type * as migrations_backfillHospitalityConnectCodeInternal from "../migrations/backfillHospitalityConnectCodeInternal.js";
import type * as migrations_backfillHospitalityCreateTypeInternal from "../migrations/backfillHospitalityCreateTypeInternal.js";
import type * as migrations_backfillHospitalityImagesInternal from "../migrations/backfillHospitalityImagesInternal.js";
import type * as migrations_backfillPartnershipCreateTypeInternal from "../migrations/backfillPartnershipCreateTypeInternal.js";
import type * as migrations_backfillPartnershipOwnerIdsInternal from "../migrations/backfillPartnershipOwnerIdsInternal.js";
import type * as migrations_dropAccommodationDescriptionInternal from "../migrations/dropAccommodationDescriptionInternal.js";
import type * as migrations_dropHospitalityVisibilityInternal from "../migrations/dropHospitalityVisibilityInternal.js";
import type * as pages_adminAnalytics_queries_fetchAdminAnalyticsOverviewPage from "../pages/adminAnalytics/queries/fetchAdminAnalyticsOverviewPage.js";
import type * as pages_adminAnalytics_types_adminAnalyticsTypes from "../pages/adminAnalytics/types/adminAnalyticsTypes.js";
import type * as pages_adminDashboard_helpers_countGuests from "../pages/adminDashboard/helpers/countGuests.js";
import type * as pages_adminDashboard_queries_fetchAdminDashboardPage from "../pages/adminDashboard/queries/fetchAdminDashboardPage.js";
import type * as pages_adminDashboard_types_adminDashboardTypes from "../pages/adminDashboard/types/adminDashboardTypes.js";
import type * as pages_userAnalytics_helpers_getUserAnalyticsChartData from "../pages/userAnalytics/helpers/getUserAnalyticsChartData.js";
import type * as pages_userAnalytics_queries_fetchUserAnalyticsAccommodationPage from "../pages/userAnalytics/queries/fetchUserAnalyticsAccommodationPage.js";
import type * as pages_userAnalytics_queries_fetchUserAnalyticsAccommodationsPage from "../pages/userAnalytics/queries/fetchUserAnalyticsAccommodationsPage.js";
import type * as pages_userAnalytics_queries_fetchUserAnalyticsHospitalitiesPage from "../pages/userAnalytics/queries/fetchUserAnalyticsHospitalitiesPage.js";
import type * as pages_userAnalytics_queries_fetchUserAnalyticsHospitalityPage from "../pages/userAnalytics/queries/fetchUserAnalyticsHospitalityPage.js";
import type * as pages_userAnalytics_queries_fetchUserAnalyticsOverviewPage from "../pages/userAnalytics/queries/fetchUserAnalyticsOverviewPage.js";
import type * as pages_userAnalytics_queries_fetchUserAnalyticsReservationsPage from "../pages/userAnalytics/queries/fetchUserAnalyticsReservationsPage.js";
import type * as pages_userAnalytics_types_userAnalyticsTypes from "../pages/userAnalytics/types/userAnalyticsTypes.js";
import type * as pages_userDashboard_helpers_getUserDashboardPendingReservations from "../pages/userDashboard/helpers/getUserDashboardPendingReservations.js";
import type * as pages_userDashboard_helpers_getUserDashboardStats from "../pages/userDashboard/helpers/getUserDashboardStats.js";
import type * as pages_userDashboard_queries_fetchUserDashboardPendingReservations from "../pages/userDashboard/queries/fetchUserDashboardPendingReservations.js";
import type * as pages_userDashboard_queries_fetchUserDashboardStats from "../pages/userDashboard/queries/fetchUserDashboardStats.js";
import type * as pages_userDashboard_types_userDashboardTypes from "../pages/userDashboard/types/userDashboardTypes.js";
import type * as rateLimits_convexCreateRateLimit from "../rateLimits/convexCreateRateLimit.js";
import type * as rateLimits_convexCreateRateLimitInternal from "../rateLimits/convexCreateRateLimitInternal.js";
import type * as rateLimits_enforceRateLimit from "../rateLimits/enforceRateLimit.js";
import type * as rateLimits_keys from "../rateLimits/keys.js";
import type * as rateLimits_registry from "../rateLimits/registry.js";
import type * as rateLimits_searchRateLimitMutations from "../rateLimits/searchRateLimitMutations.js";
import type * as resend from "../resend.js";
import type * as schemas_mutationResult from "../schemas/mutationResult.js";
import type * as storage_crons_cleanupOrphanDataR2 from "../storage/crons/cleanupOrphanDataR2.js";
import type * as storage_r2_buildR2PublicObjectUrl from "../storage/r2/buildR2PublicObjectUrl.js";
import type * as storage_r2_deleteUploadedFilesByKeys from "../storage/r2/deleteUploadedFilesByKeys.js";
import type * as storage_r2_r2 from "../storage/r2/r2.js";
import type * as storage_r2_resolveStoredFileUrl from "../storage/r2/resolveStoredFileUrl.js";
import type * as storage_r2_schemas_uploadedFilesR2Schemas from "../storage/r2/schemas/uploadedFilesR2Schemas.js";
import type * as storage_r2_uploadedFilesR2 from "../storage/r2/uploadedFilesR2.js";
import type * as storage_registerStorageCrons from "../storage/registerStorageCrons.js";
import type * as tables_accommodations_helpers_allocateScanToken from "../tables/accommodations/helpers/allocateScanToken.js";
import type * as tables_accommodations_helpers_cascadeAccommodationChildren from "../tables/accommodations/helpers/cascadeAccommodationChildren.js";
import type * as tables_accommodations_helpers_cleanupAccommodationCoverImages from "../tables/accommodations/helpers/cleanupAccommodationCoverImages.js";
import type * as tables_accommodations_helpers_getAccommodationByIdSafe from "../tables/accommodations/helpers/getAccommodationByIdSafe.js";
import type * as tables_accommodations_helpers_getAccommodationForEdit from "../tables/accommodations/helpers/getAccommodationForEdit.js";
import type * as tables_accommodations_helpers_getAccommodationsByIds from "../tables/accommodations/helpers/getAccommodationsByIds.js";
import type * as tables_accommodations_helpers_getOwnedAccommodation from "../tables/accommodations/helpers/getOwnedAccommodation.js";
import type * as tables_accommodations_helpers_getUserOwnedAccommodations from "../tables/accommodations/helpers/getUserOwnedAccommodations.js";
import type * as tables_accommodations_mutations_adminCreateAccommodation from "../tables/accommodations/mutations/adminCreateAccommodation.js";
import type * as tables_accommodations_mutations_createAccommodationForOwner from "../tables/accommodations/mutations/createAccommodationForOwner.js";
import type * as tables_accommodations_mutations_createMyAccommodation from "../tables/accommodations/mutations/createMyAccommodation.js";
import type * as tables_accommodations_mutations_deleteAccommodations from "../tables/accommodations/mutations/deleteAccommodations.js";
import type * as tables_accommodations_mutations_deleteMyAccommodation from "../tables/accommodations/mutations/deleteMyAccommodation.js";
import type * as tables_accommodations_mutations_updateAccommodation from "../tables/accommodations/mutations/updateAccommodation.js";
import type * as tables_accommodations_queries_fetchAccommodationDetails from "../tables/accommodations/queries/fetchAccommodationDetails.js";
import type * as tables_accommodations_queries_fetchAllAccommodations from "../tables/accommodations/queries/fetchAllAccommodations.js";
import type * as tables_accommodations_queries_fetchMyAccommodationForEdit from "../tables/accommodations/queries/fetchMyAccommodationForEdit.js";
import type * as tables_accommodations_queries_fetchMyAccommodations from "../tables/accommodations/queries/fetchMyAccommodations.js";
import type * as tables_accommodations_queries_fetchMyAccommodationsSummary from "../tables/accommodations/queries/fetchMyAccommodationsSummary.js";
import type * as tables_accommodations_queries_searchAllAccommodations from "../tables/accommodations/queries/searchAllAccommodations.js";
import type * as tables_accommodations_queries_searchMyAccommodations from "../tables/accommodations/queries/searchMyAccommodations.js";
import type * as tables_accommodations_schemas_accommodationsSchemas from "../tables/accommodations/schemas/accommodationsSchemas.js";
import type * as tables_accommodations_types_accommodationsTypes from "../tables/accommodations/types/accommodationsTypes.js";
import type * as tables_accommodations_utils_convexGenerateScanToken from "../tables/accommodations/utils/convexGenerateScanToken.js";
import type * as tables_accommodations_validators_accommodationQueryValidators from "../tables/accommodations/validators/accommodationQueryValidators.js";
import type * as tables_auditLog_auditLogConfigs from "../tables/auditLog/auditLogConfigs.js";
import type * as tables_auditLog_crons_auditLogCron from "../tables/auditLog/crons/auditLogCron.js";
import type * as tables_auditLog_helpers_auditLogInternal from "../tables/auditLog/helpers/auditLogInternal.js";
import type * as tables_auditLog_helpers_logAudit from "../tables/auditLog/helpers/logAudit.js";
import type * as tables_auditLog_index from "../tables/auditLog/index.js";
import type * as tables_auditLog_queries_auditLogQueries from "../tables/auditLog/queries/auditLogQueries.js";
import type * as tables_auditLog_registerAuditLogCrons from "../tables/auditLog/registerAuditLogCrons.js";
import type * as tables_auditLog_schemas_auditLogSchema from "../tables/auditLog/schemas/auditLogSchema.js";
import type * as tables_auditLog_utils_auditLogUtils from "../tables/auditLog/utils/auditLogUtils.js";
import type * as tables_guests_actions_createGuestConvexAuthToken from "../tables/guests/actions/createGuestConvexAuthToken.js";
import type * as tables_guests_crons_expireGuestsCron from "../tables/guests/crons/expireGuestsCron.js";
import type * as tables_guests_helpers_accommodationHasActiveGuest from "../tables/guests/helpers/accommodationHasActiveGuest.js";
import type * as tables_guests_helpers_getActiveGuestSession from "../tables/guests/helpers/getActiveGuestSession.js";
import type * as tables_guests_helpers_getActiveGuestSessionFromAuth from "../tables/guests/helpers/getActiveGuestSessionFromAuth.js";
import type * as tables_guests_helpers_resolveGuestSessionFromCookie from "../tables/guests/helpers/resolveGuestSessionFromCookie.js";
import type * as tables_guests_mutations_createGuest from "../tables/guests/mutations/createGuest.js";
import type * as tables_guests_mutations_createGuestSharingCode from "../tables/guests/mutations/createGuestSharingCode.js";
import type * as tables_guests_mutations_joinGuestBySharingCode from "../tables/guests/mutations/joinGuestBySharingCode.js";
import type * as tables_guests_queries_fetchCurrentGuest from "../tables/guests/queries/fetchCurrentGuest.js";
import type * as tables_guests_queries_fetchGuestConvexJwks from "../tables/guests/queries/fetchGuestConvexJwks.js";
import type * as tables_guests_queries_fetchGuestSessionFromCookie from "../tables/guests/queries/fetchGuestSessionFromCookie.js";
import type * as tables_guests_queries_fetchGuestSessionFromCookieInternal from "../tables/guests/queries/fetchGuestSessionFromCookieInternal.js";
import type * as tables_guests_registerGuestCrons from "../tables/guests/registerGuestCrons.js";
import type * as tables_guests_schemas_guestsSchemas from "../tables/guests/schemas/guestsSchemas.js";
import type * as tables_guests_types_guestsTypes from "../tables/guests/types/guestsTypes.js";
import type * as tables_guests_utils_guestConvexJwt from "../tables/guests/utils/guestConvexJwt.js";
import type * as tables_guests_utils_guestIssuer from "../tables/guests/utils/guestIssuer.js";
import type * as tables_guests_utils_guestSessionToken from "../tables/guests/utils/guestSessionToken.js";
import type * as tables_guests_utils_guestStayCookieCrypto from "../tables/guests/utils/guestStayCookieCrypto.js";
import type * as tables_guests_utils_isGuestStayIdentity from "../tables/guests/utils/isGuestStayIdentity.js";
import type * as tables_guests_validators_guestQueryValidators from "../tables/guests/validators/guestQueryValidators.js";
import type * as tables_hospitalities_helpers_cascadeHospitalityChildren from "../tables/hospitalities/helpers/cascadeHospitalityChildren.js";
import type * as tables_hospitalities_helpers_cleanupHospitalityFiles from "../tables/hospitalities/helpers/cleanupHospitalityFiles.js";
import type * as tables_hospitalities_helpers_connectCode from "../tables/hospitalities/helpers/connectCode.js";
import type * as tables_hospitalities_helpers_ensureHospitalityCreateAccess from "../tables/hospitalities/helpers/ensureHospitalityCreateAccess.js";
import type * as tables_hospitalities_helpers_generateUniqueConnectCode from "../tables/hospitalities/helpers/generateUniqueConnectCode.js";
import type * as tables_hospitalities_helpers_getHospitalitiesByIds from "../tables/hospitalities/helpers/getHospitalitiesByIds.js";
import type * as tables_hospitalities_helpers_getHospitalityForEdit from "../tables/hospitalities/helpers/getHospitalityForEdit.js";
import type * as tables_hospitalities_helpers_getOwnedHospitality from "../tables/hospitalities/helpers/getOwnedHospitality.js";
import type * as tables_hospitalities_helpers_getUserOwnedHospitalities from "../tables/hospitalities/helpers/getUserOwnedHospitalities.js";
import type * as tables_hospitalities_helpers_resolveMenuFile from "../tables/hospitalities/helpers/resolveMenuFile.js";
import type * as tables_hospitalities_mutations_createHospitality from "../tables/hospitalities/mutations/createHospitality.js";
import type * as tables_hospitalities_mutations_createUserHospitality from "../tables/hospitalities/mutations/createUserHospitality.js";
import type * as tables_hospitalities_mutations_deleteHospitalities from "../tables/hospitalities/mutations/deleteHospitalities.js";
import type * as tables_hospitalities_mutations_deleteMyHospitality from "../tables/hospitalities/mutations/deleteMyHospitality.js";
import type * as tables_hospitalities_mutations_setHospitalityCreateType from "../tables/hospitalities/mutations/setHospitalityCreateType.js";
import type * as tables_hospitalities_mutations_updateHospitality from "../tables/hospitalities/mutations/updateHospitality.js";
import type * as tables_hospitalities_mutations_viewHospitality from "../tables/hospitalities/mutations/viewHospitality.js";
import type * as tables_hospitalities_queries_fetchActivePlatformHospitalities from "../tables/hospitalities/queries/fetchActivePlatformHospitalities.js";
import type * as tables_hospitalities_queries_fetchAllHospitalities from "../tables/hospitalities/queries/fetchAllHospitalities.js";
import type * as tables_hospitalities_queries_fetchHospitalityDetails from "../tables/hospitalities/queries/fetchHospitalityDetails.js";
import type * as tables_hospitalities_queries_fetchHospitalityForAdminEdit from "../tables/hospitalities/queries/fetchHospitalityForAdminEdit.js";
import type * as tables_hospitalities_queries_fetchMyHospitalities from "../tables/hospitalities/queries/fetchMyHospitalities.js";
import type * as tables_hospitalities_queries_fetchMyHospitalitiesSummary from "../tables/hospitalities/queries/fetchMyHospitalitiesSummary.js";
import type * as tables_hospitalities_queries_fetchMyHospitalityForEdit from "../tables/hospitalities/queries/fetchMyHospitalityForEdit.js";
import type * as tables_hospitalities_queries_lookupCustomPartnershipFormVenueByConnectCode from "../tables/hospitalities/queries/lookupCustomPartnershipFormVenueByConnectCode.js";
import type * as tables_hospitalities_queries_searchAllHospitalities from "../tables/hospitalities/queries/searchAllHospitalities.js";
import type * as tables_hospitalities_queries_searchMyHospitalities from "../tables/hospitalities/queries/searchMyHospitalities.js";
import type * as tables_hospitalities_schemas_hospitalitiesSchemas from "../tables/hospitalities/schemas/hospitalitiesSchemas.js";
import type * as tables_hospitalities_types_hospitalitiesTypes from "../tables/hospitalities/types/hospitalitiesTypes.js";
import type * as tables_hospitalities_utils_isPlatformHospitality from "../tables/hospitalities/utils/isPlatformHospitality.js";
import type * as tables_hospitalities_validators_hospitalityQueryValidators from "../tables/hospitalities/validators/hospitalityQueryValidators.js";
import type * as tables_partnershipRequests_helpers_enrichPartnershipRequestItems from "../tables/partnershipRequests/helpers/enrichPartnershipRequestItems.js";
import type * as tables_partnershipRequests_queries_fetchPartnershipsRequestsReceived from "../tables/partnershipRequests/queries/fetchPartnershipsRequestsReceived.js";
import type * as tables_partnershipRequests_queries_fetchPartnershipsRequestsSent from "../tables/partnershipRequests/queries/fetchPartnershipsRequestsSent.js";
import type * as tables_partnershipRequests_schemas_partnershipRequestsSchemas from "../tables/partnershipRequests/schemas/partnershipRequestsSchemas.js";
import type * as tables_partnerships_helpers_decrementActivePartnershipCounters from "../tables/partnerships/helpers/decrementActivePartnershipCounters.js";
import type * as tables_partnerships_helpers_ensureCustomPartnershipAccess from "../tables/partnerships/helpers/ensureCustomPartnershipAccess.js";
import type * as tables_partnerships_helpers_getActiveAccommodationPartnership from "../tables/partnerships/helpers/getActiveAccommodationPartnership.js";
import type * as tables_partnerships_helpers_getActivePartnershipsByAccommodation from "../tables/partnerships/helpers/getActivePartnershipsByAccommodation.js";
import type * as tables_partnerships_helpers_getActivePartnershipsByHospitality from "../tables/partnerships/helpers/getActivePartnershipsByHospitality.js";
import type * as tables_partnerships_helpers_getCustomPartnershipsForStaySafe from "../tables/partnerships/helpers/getCustomPartnershipsForStaySafe.js";
import type * as tables_partnerships_helpers_hasActivePartnership from "../tables/partnerships/helpers/hasActivePartnership.js";
import type * as tables_partnerships_helpers_insertPartnership from "../tables/partnerships/helpers/insertPartnership.js";
import type * as tables_partnerships_helpers_reactivatePartnership from "../tables/partnerships/helpers/reactivatePartnership.js";
import type * as tables_partnerships_helpers_resolveGuestPartnershipOffer from "../tables/partnerships/helpers/resolveGuestPartnershipOffer.js";
import type * as tables_partnerships_mutations_acceptPartnershipRequest from "../tables/partnerships/mutations/acceptPartnershipRequest.js";
import type * as tables_partnerships_mutations_createCustomPartnership from "../tables/partnerships/mutations/createCustomPartnership.js";
import type * as tables_partnerships_mutations_createPartnership from "../tables/partnerships/mutations/createPartnership.js";
import type * as tables_partnerships_mutations_declinePartnershipRequest from "../tables/partnerships/mutations/declinePartnershipRequest.js";
import type * as tables_partnerships_mutations_deletePartnerships from "../tables/partnerships/mutations/deletePartnerships.js";
import type * as tables_partnerships_mutations_revokePartnership from "../tables/partnerships/mutations/revokePartnership.js";
import type * as tables_partnerships_mutations_updatePartnershipBenefit from "../tables/partnerships/mutations/updatePartnershipBenefit.js";
import type * as tables_partnerships_queries_fetchAccommodationCustomPartnerships from "../tables/partnerships/queries/fetchAccommodationCustomPartnerships.js";
import type * as tables_partnerships_queries_fetchActivePartnershipsSafe from "../tables/partnerships/queries/fetchActivePartnershipsSafe.js";
import type * as tables_partnerships_queries_fetchAllPartnershipsAdmin from "../tables/partnerships/queries/fetchAllPartnershipsAdmin.js";
import type * as tables_partnerships_queries_fetchStayPlatformPartnerships from "../tables/partnerships/queries/fetchStayPlatformPartnerships.js";
import type * as tables_partnerships_schemas_partnershipsSchemas from "../tables/partnerships/schemas/partnershipsSchemas.js";
import type * as tables_partnerships_types_partnershipsTypes from "../tables/partnerships/types/partnershipsTypes.js";
import type * as tables_partnerships_utils_parsePartnershipBenefit from "../tables/partnerships/utils/parsePartnershipBenefit.js";
import type * as tables_partnerships_validators_partnershipQueryValidators from "../tables/partnerships/validators/partnershipQueryValidators.js";
import type * as tables_proTrials_crons_proTrialCron from "../tables/proTrials/crons/proTrialCron.js";
import type * as tables_proTrials_helpers_proTrial from "../tables/proTrials/helpers/proTrial.js";
import type * as tables_proTrials_mutations_startProTrial from "../tables/proTrials/mutations/startProTrial.js";
import type * as tables_proTrials_registerProTrialCrons from "../tables/proTrials/registerProTrialCrons.js";
import type * as tables_proTrials_schemas_proTrialsSchemas from "../tables/proTrials/schemas/proTrialsSchemas.js";
import type * as tables_reports_mutations_createReport from "../tables/reports/mutations/createReport.js";
import type * as tables_reports_queries_fetchReports from "../tables/reports/queries/fetchReports.js";
import type * as tables_reports_schemas_reportsSchemas from "../tables/reports/schemas/reportsSchemas.js";
import type * as tables_reservations_emails_sendReservationEmailToGuest from "../tables/reservations/emails/sendReservationEmailToGuest.js";
import type * as tables_reservations_emails_sendReservationEmailToHospitalityOwner from "../tables/reservations/emails/sendReservationEmailToHospitalityOwner.js";
import type * as tables_reservations_helpers_cancelPendingReservationsForGuest from "../tables/reservations/helpers/cancelPendingReservationsForGuest.js";
import type * as tables_reservations_helpers_createFetchReservationsQuery from "../tables/reservations/helpers/createFetchReservationsQuery.js";
import type * as tables_reservations_helpers_getGuestActiveHospitalityReservation from "../tables/reservations/helpers/getGuestActiveHospitalityReservation.js";
import type * as tables_reservations_helpers_hospitalityHasOpenReservations from "../tables/reservations/helpers/hospitalityHasOpenReservations.js";
import type * as tables_reservations_mutations_cancelReservation from "../tables/reservations/mutations/cancelReservation.js";
import type * as tables_reservations_mutations_confirmReservation from "../tables/reservations/mutations/confirmReservation.js";
import type * as tables_reservations_mutations_createReservation from "../tables/reservations/mutations/createReservation.js";
import type * as tables_reservations_mutations_markReservationNoShow from "../tables/reservations/mutations/markReservationNoShow.js";
import type * as tables_reservations_queries_fetchCancelledReservations from "../tables/reservations/queries/fetchCancelledReservations.js";
import type * as tables_reservations_queries_fetchConfirmedReservations from "../tables/reservations/queries/fetchConfirmedReservations.js";
import type * as tables_reservations_queries_fetchNoShowReservations from "../tables/reservations/queries/fetchNoShowReservations.js";
import type * as tables_reservations_queries_fetchPendingReservations from "../tables/reservations/queries/fetchPendingReservations.js";
import type * as tables_reservations_queries_fetchReservationsSummary from "../tables/reservations/queries/fetchReservationsSummary.js";
import type * as tables_reservations_schemas_reservationsSchemas from "../tables/reservations/schemas/reservationsSchemas.js";
import type * as tables_reservations_types_reservationsTypes from "../tables/reservations/types/reservationsTypes.js";
import type * as tables_reservations_validators_reservationQueryValidators from "../tables/reservations/validators/reservationQueryValidators.js";
import type * as tables_users_userMutations from "../tables/users/userMutations.js";
import type * as tables_users_userQueries from "../tables/users/userQueries.js";
import type * as types_convexTypes from "../types/convexTypes.js";
import type * as utils_convexValidationUtils from "../utils/convexValidationUtils.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  analytics: typeof analytics;
  "analytics/analyticsConstants": typeof analytics_analyticsConstants;
  "analytics/utils/analyticsQueryRange": typeof analytics_utils_analyticsQueryRange;
  "analytics/utils/buildAnalyticsRows": typeof analytics_utils_buildAnalyticsRows;
  "analytics/utils/buildUserAnalyticsChartData": typeof analytics_utils_buildUserAnalyticsChartData;
  "analytics/utils/comparedMetricUtils": typeof analytics_utils_comparedMetricUtils;
  "analytics/utils/getAnalyticsMetricValue": typeof analytics_utils_getAnalyticsMetricValue;
  "analytics/utils/sortAnalyticsItemsByMetric": typeof analytics_utils_sortAnalyticsItemsByMetric;
  "auth/assertTrustedServer": typeof auth_assertTrustedServer;
  "auth/auth": typeof auth_auth;
  "auth/authRoutes": typeof auth_authRoutes;
  "auth/convexCreateAuthRateLimitHook": typeof auth_convexCreateAuthRateLimitHook;
  "auth/emails/sendVerificationOTP": typeof auth_emails_sendVerificationOTP;
  "auth/guestConvexAuth": typeof auth_guestConvexAuth;
  "auth/helpers/getAuthUserId": typeof auth_helpers_getAuthUserId;
  "auth/helpers/isAdminUser": typeof auth_helpers_isAdminUser;
  "auth/middleware/authMiddleware": typeof auth_middleware_authMiddleware;
  "auth/queries/authQueries": typeof auth_queries_authQueries;
  "auth/types/types": typeof auth_types_types;
  "auth/utils/getEmailFromAuthBody": typeof auth_utils_getEmailFromAuthBody;
  convexRateLimiter: typeof convexRateLimiter;
  crons: typeof crons;
  "email/templates/baseEmailTemplate": typeof email_templates_baseEmailTemplate;
  "email/templates/emailFooterTemplate": typeof email_templates_emailFooterTemplate;
  "email/templates/emailHeaderTemplate": typeof email_templates_emailHeaderTemplate;
  "email/utils/convexEmailUtils": typeof email_utils_convexEmailUtils;
  "helpers/convexGetRateLimitedUserId": typeof helpers_convexGetRateLimitedUserId;
  "helpers/counterKeys": typeof helpers_counterKeys;
  "helpers/createDeleteMutation": typeof helpers_createDeleteMutation;
  "helpers/createProjection": typeof helpers_createProjection;
  "helpers/fetchOptimized/createSearchQuery": typeof helpers_fetchOptimized_createSearchQuery;
  "helpers/fetchOptimized/fetchOptimized": typeof helpers_fetchOptimized_fetchOptimized;
  "helpers/fetchOptimized/index": typeof helpers_fetchOptimized_index;
  "helpers/fetchOptimized/kit": typeof helpers_fetchOptimized_kit;
  "helpers/fetchOptimized/types": typeof helpers_fetchOptimized_types;
  "helpers/ownerCounterHelpers": typeof helpers_ownerCounterHelpers;
  "helpers/paginationHelpers": typeof helpers_paginationHelpers;
  "helpers/resolveUploadedImages": typeof helpers_resolveUploadedImages;
  "helpers/uniqueIds": typeof helpers_uniqueIds;
  http: typeof http;
  "migrations/backfillCountersInternal": typeof migrations_backfillCountersInternal;
  "migrations/backfillHospitalityConnectCodeInternal": typeof migrations_backfillHospitalityConnectCodeInternal;
  "migrations/backfillHospitalityCreateTypeInternal": typeof migrations_backfillHospitalityCreateTypeInternal;
  "migrations/backfillHospitalityImagesInternal": typeof migrations_backfillHospitalityImagesInternal;
  "migrations/backfillPartnershipCreateTypeInternal": typeof migrations_backfillPartnershipCreateTypeInternal;
  "migrations/backfillPartnershipOwnerIdsInternal": typeof migrations_backfillPartnershipOwnerIdsInternal;
  "migrations/dropAccommodationDescriptionInternal": typeof migrations_dropAccommodationDescriptionInternal;
  "migrations/dropHospitalityVisibilityInternal": typeof migrations_dropHospitalityVisibilityInternal;
  "pages/adminAnalytics/queries/fetchAdminAnalyticsOverviewPage": typeof pages_adminAnalytics_queries_fetchAdminAnalyticsOverviewPage;
  "pages/adminAnalytics/types/adminAnalyticsTypes": typeof pages_adminAnalytics_types_adminAnalyticsTypes;
  "pages/adminDashboard/helpers/countGuests": typeof pages_adminDashboard_helpers_countGuests;
  "pages/adminDashboard/queries/fetchAdminDashboardPage": typeof pages_adminDashboard_queries_fetchAdminDashboardPage;
  "pages/adminDashboard/types/adminDashboardTypes": typeof pages_adminDashboard_types_adminDashboardTypes;
  "pages/userAnalytics/helpers/getUserAnalyticsChartData": typeof pages_userAnalytics_helpers_getUserAnalyticsChartData;
  "pages/userAnalytics/queries/fetchUserAnalyticsAccommodationPage": typeof pages_userAnalytics_queries_fetchUserAnalyticsAccommodationPage;
  "pages/userAnalytics/queries/fetchUserAnalyticsAccommodationsPage": typeof pages_userAnalytics_queries_fetchUserAnalyticsAccommodationsPage;
  "pages/userAnalytics/queries/fetchUserAnalyticsHospitalitiesPage": typeof pages_userAnalytics_queries_fetchUserAnalyticsHospitalitiesPage;
  "pages/userAnalytics/queries/fetchUserAnalyticsHospitalityPage": typeof pages_userAnalytics_queries_fetchUserAnalyticsHospitalityPage;
  "pages/userAnalytics/queries/fetchUserAnalyticsOverviewPage": typeof pages_userAnalytics_queries_fetchUserAnalyticsOverviewPage;
  "pages/userAnalytics/queries/fetchUserAnalyticsReservationsPage": typeof pages_userAnalytics_queries_fetchUserAnalyticsReservationsPage;
  "pages/userAnalytics/types/userAnalyticsTypes": typeof pages_userAnalytics_types_userAnalyticsTypes;
  "pages/userDashboard/helpers/getUserDashboardPendingReservations": typeof pages_userDashboard_helpers_getUserDashboardPendingReservations;
  "pages/userDashboard/helpers/getUserDashboardStats": typeof pages_userDashboard_helpers_getUserDashboardStats;
  "pages/userDashboard/queries/fetchUserDashboardPendingReservations": typeof pages_userDashboard_queries_fetchUserDashboardPendingReservations;
  "pages/userDashboard/queries/fetchUserDashboardStats": typeof pages_userDashboard_queries_fetchUserDashboardStats;
  "pages/userDashboard/types/userDashboardTypes": typeof pages_userDashboard_types_userDashboardTypes;
  "rateLimits/convexCreateRateLimit": typeof rateLimits_convexCreateRateLimit;
  "rateLimits/convexCreateRateLimitInternal": typeof rateLimits_convexCreateRateLimitInternal;
  "rateLimits/enforceRateLimit": typeof rateLimits_enforceRateLimit;
  "rateLimits/keys": typeof rateLimits_keys;
  "rateLimits/registry": typeof rateLimits_registry;
  "rateLimits/searchRateLimitMutations": typeof rateLimits_searchRateLimitMutations;
  resend: typeof resend;
  "schemas/mutationResult": typeof schemas_mutationResult;
  "storage/crons/cleanupOrphanDataR2": typeof storage_crons_cleanupOrphanDataR2;
  "storage/r2/buildR2PublicObjectUrl": typeof storage_r2_buildR2PublicObjectUrl;
  "storage/r2/deleteUploadedFilesByKeys": typeof storage_r2_deleteUploadedFilesByKeys;
  "storage/r2/r2": typeof storage_r2_r2;
  "storage/r2/resolveStoredFileUrl": typeof storage_r2_resolveStoredFileUrl;
  "storage/r2/schemas/uploadedFilesR2Schemas": typeof storage_r2_schemas_uploadedFilesR2Schemas;
  "storage/r2/uploadedFilesR2": typeof storage_r2_uploadedFilesR2;
  "storage/registerStorageCrons": typeof storage_registerStorageCrons;
  "tables/accommodations/helpers/allocateScanToken": typeof tables_accommodations_helpers_allocateScanToken;
  "tables/accommodations/helpers/cascadeAccommodationChildren": typeof tables_accommodations_helpers_cascadeAccommodationChildren;
  "tables/accommodations/helpers/cleanupAccommodationCoverImages": typeof tables_accommodations_helpers_cleanupAccommodationCoverImages;
  "tables/accommodations/helpers/getAccommodationByIdSafe": typeof tables_accommodations_helpers_getAccommodationByIdSafe;
  "tables/accommodations/helpers/getAccommodationForEdit": typeof tables_accommodations_helpers_getAccommodationForEdit;
  "tables/accommodations/helpers/getAccommodationsByIds": typeof tables_accommodations_helpers_getAccommodationsByIds;
  "tables/accommodations/helpers/getOwnedAccommodation": typeof tables_accommodations_helpers_getOwnedAccommodation;
  "tables/accommodations/helpers/getUserOwnedAccommodations": typeof tables_accommodations_helpers_getUserOwnedAccommodations;
  "tables/accommodations/mutations/adminCreateAccommodation": typeof tables_accommodations_mutations_adminCreateAccommodation;
  "tables/accommodations/mutations/createAccommodationForOwner": typeof tables_accommodations_mutations_createAccommodationForOwner;
  "tables/accommodations/mutations/createMyAccommodation": typeof tables_accommodations_mutations_createMyAccommodation;
  "tables/accommodations/mutations/deleteAccommodations": typeof tables_accommodations_mutations_deleteAccommodations;
  "tables/accommodations/mutations/deleteMyAccommodation": typeof tables_accommodations_mutations_deleteMyAccommodation;
  "tables/accommodations/mutations/updateAccommodation": typeof tables_accommodations_mutations_updateAccommodation;
  "tables/accommodations/queries/fetchAccommodationDetails": typeof tables_accommodations_queries_fetchAccommodationDetails;
  "tables/accommodations/queries/fetchAllAccommodations": typeof tables_accommodations_queries_fetchAllAccommodations;
  "tables/accommodations/queries/fetchMyAccommodationForEdit": typeof tables_accommodations_queries_fetchMyAccommodationForEdit;
  "tables/accommodations/queries/fetchMyAccommodations": typeof tables_accommodations_queries_fetchMyAccommodations;
  "tables/accommodations/queries/fetchMyAccommodationsSummary": typeof tables_accommodations_queries_fetchMyAccommodationsSummary;
  "tables/accommodations/queries/searchAllAccommodations": typeof tables_accommodations_queries_searchAllAccommodations;
  "tables/accommodations/queries/searchMyAccommodations": typeof tables_accommodations_queries_searchMyAccommodations;
  "tables/accommodations/schemas/accommodationsSchemas": typeof tables_accommodations_schemas_accommodationsSchemas;
  "tables/accommodations/types/accommodationsTypes": typeof tables_accommodations_types_accommodationsTypes;
  "tables/accommodations/utils/convexGenerateScanToken": typeof tables_accommodations_utils_convexGenerateScanToken;
  "tables/accommodations/validators/accommodationQueryValidators": typeof tables_accommodations_validators_accommodationQueryValidators;
  "tables/auditLog/auditLogConfigs": typeof tables_auditLog_auditLogConfigs;
  "tables/auditLog/crons/auditLogCron": typeof tables_auditLog_crons_auditLogCron;
  "tables/auditLog/helpers/auditLogInternal": typeof tables_auditLog_helpers_auditLogInternal;
  "tables/auditLog/helpers/logAudit": typeof tables_auditLog_helpers_logAudit;
  "tables/auditLog/index": typeof tables_auditLog_index;
  "tables/auditLog/queries/auditLogQueries": typeof tables_auditLog_queries_auditLogQueries;
  "tables/auditLog/registerAuditLogCrons": typeof tables_auditLog_registerAuditLogCrons;
  "tables/auditLog/schemas/auditLogSchema": typeof tables_auditLog_schemas_auditLogSchema;
  "tables/auditLog/utils/auditLogUtils": typeof tables_auditLog_utils_auditLogUtils;
  "tables/guests/actions/createGuestConvexAuthToken": typeof tables_guests_actions_createGuestConvexAuthToken;
  "tables/guests/crons/expireGuestsCron": typeof tables_guests_crons_expireGuestsCron;
  "tables/guests/helpers/accommodationHasActiveGuest": typeof tables_guests_helpers_accommodationHasActiveGuest;
  "tables/guests/helpers/getActiveGuestSession": typeof tables_guests_helpers_getActiveGuestSession;
  "tables/guests/helpers/getActiveGuestSessionFromAuth": typeof tables_guests_helpers_getActiveGuestSessionFromAuth;
  "tables/guests/helpers/resolveGuestSessionFromCookie": typeof tables_guests_helpers_resolveGuestSessionFromCookie;
  "tables/guests/mutations/createGuest": typeof tables_guests_mutations_createGuest;
  "tables/guests/mutations/createGuestSharingCode": typeof tables_guests_mutations_createGuestSharingCode;
  "tables/guests/mutations/joinGuestBySharingCode": typeof tables_guests_mutations_joinGuestBySharingCode;
  "tables/guests/queries/fetchCurrentGuest": typeof tables_guests_queries_fetchCurrentGuest;
  "tables/guests/queries/fetchGuestConvexJwks": typeof tables_guests_queries_fetchGuestConvexJwks;
  "tables/guests/queries/fetchGuestSessionFromCookie": typeof tables_guests_queries_fetchGuestSessionFromCookie;
  "tables/guests/queries/fetchGuestSessionFromCookieInternal": typeof tables_guests_queries_fetchGuestSessionFromCookieInternal;
  "tables/guests/registerGuestCrons": typeof tables_guests_registerGuestCrons;
  "tables/guests/schemas/guestsSchemas": typeof tables_guests_schemas_guestsSchemas;
  "tables/guests/types/guestsTypes": typeof tables_guests_types_guestsTypes;
  "tables/guests/utils/guestConvexJwt": typeof tables_guests_utils_guestConvexJwt;
  "tables/guests/utils/guestIssuer": typeof tables_guests_utils_guestIssuer;
  "tables/guests/utils/guestSessionToken": typeof tables_guests_utils_guestSessionToken;
  "tables/guests/utils/guestStayCookieCrypto": typeof tables_guests_utils_guestStayCookieCrypto;
  "tables/guests/utils/isGuestStayIdentity": typeof tables_guests_utils_isGuestStayIdentity;
  "tables/guests/validators/guestQueryValidators": typeof tables_guests_validators_guestQueryValidators;
  "tables/hospitalities/helpers/cascadeHospitalityChildren": typeof tables_hospitalities_helpers_cascadeHospitalityChildren;
  "tables/hospitalities/helpers/cleanupHospitalityFiles": typeof tables_hospitalities_helpers_cleanupHospitalityFiles;
  "tables/hospitalities/helpers/connectCode": typeof tables_hospitalities_helpers_connectCode;
  "tables/hospitalities/helpers/ensureHospitalityCreateAccess": typeof tables_hospitalities_helpers_ensureHospitalityCreateAccess;
  "tables/hospitalities/helpers/generateUniqueConnectCode": typeof tables_hospitalities_helpers_generateUniqueConnectCode;
  "tables/hospitalities/helpers/getHospitalitiesByIds": typeof tables_hospitalities_helpers_getHospitalitiesByIds;
  "tables/hospitalities/helpers/getHospitalityForEdit": typeof tables_hospitalities_helpers_getHospitalityForEdit;
  "tables/hospitalities/helpers/getOwnedHospitality": typeof tables_hospitalities_helpers_getOwnedHospitality;
  "tables/hospitalities/helpers/getUserOwnedHospitalities": typeof tables_hospitalities_helpers_getUserOwnedHospitalities;
  "tables/hospitalities/helpers/resolveMenuFile": typeof tables_hospitalities_helpers_resolveMenuFile;
  "tables/hospitalities/mutations/createHospitality": typeof tables_hospitalities_mutations_createHospitality;
  "tables/hospitalities/mutations/createUserHospitality": typeof tables_hospitalities_mutations_createUserHospitality;
  "tables/hospitalities/mutations/deleteHospitalities": typeof tables_hospitalities_mutations_deleteHospitalities;
  "tables/hospitalities/mutations/deleteMyHospitality": typeof tables_hospitalities_mutations_deleteMyHospitality;
  "tables/hospitalities/mutations/setHospitalityCreateType": typeof tables_hospitalities_mutations_setHospitalityCreateType;
  "tables/hospitalities/mutations/updateHospitality": typeof tables_hospitalities_mutations_updateHospitality;
  "tables/hospitalities/mutations/viewHospitality": typeof tables_hospitalities_mutations_viewHospitality;
  "tables/hospitalities/queries/fetchActivePlatformHospitalities": typeof tables_hospitalities_queries_fetchActivePlatformHospitalities;
  "tables/hospitalities/queries/fetchAllHospitalities": typeof tables_hospitalities_queries_fetchAllHospitalities;
  "tables/hospitalities/queries/fetchHospitalityDetails": typeof tables_hospitalities_queries_fetchHospitalityDetails;
  "tables/hospitalities/queries/fetchHospitalityForAdminEdit": typeof tables_hospitalities_queries_fetchHospitalityForAdminEdit;
  "tables/hospitalities/queries/fetchMyHospitalities": typeof tables_hospitalities_queries_fetchMyHospitalities;
  "tables/hospitalities/queries/fetchMyHospitalitiesSummary": typeof tables_hospitalities_queries_fetchMyHospitalitiesSummary;
  "tables/hospitalities/queries/fetchMyHospitalityForEdit": typeof tables_hospitalities_queries_fetchMyHospitalityForEdit;
  "tables/hospitalities/queries/lookupCustomPartnershipFormVenueByConnectCode": typeof tables_hospitalities_queries_lookupCustomPartnershipFormVenueByConnectCode;
  "tables/hospitalities/queries/searchAllHospitalities": typeof tables_hospitalities_queries_searchAllHospitalities;
  "tables/hospitalities/queries/searchMyHospitalities": typeof tables_hospitalities_queries_searchMyHospitalities;
  "tables/hospitalities/schemas/hospitalitiesSchemas": typeof tables_hospitalities_schemas_hospitalitiesSchemas;
  "tables/hospitalities/types/hospitalitiesTypes": typeof tables_hospitalities_types_hospitalitiesTypes;
  "tables/hospitalities/utils/isPlatformHospitality": typeof tables_hospitalities_utils_isPlatformHospitality;
  "tables/hospitalities/validators/hospitalityQueryValidators": typeof tables_hospitalities_validators_hospitalityQueryValidators;
  "tables/partnershipRequests/helpers/enrichPartnershipRequestItems": typeof tables_partnershipRequests_helpers_enrichPartnershipRequestItems;
  "tables/partnershipRequests/queries/fetchPartnershipsRequestsReceived": typeof tables_partnershipRequests_queries_fetchPartnershipsRequestsReceived;
  "tables/partnershipRequests/queries/fetchPartnershipsRequestsSent": typeof tables_partnershipRequests_queries_fetchPartnershipsRequestsSent;
  "tables/partnershipRequests/schemas/partnershipRequestsSchemas": typeof tables_partnershipRequests_schemas_partnershipRequestsSchemas;
  "tables/partnerships/helpers/decrementActivePartnershipCounters": typeof tables_partnerships_helpers_decrementActivePartnershipCounters;
  "tables/partnerships/helpers/ensureCustomPartnershipAccess": typeof tables_partnerships_helpers_ensureCustomPartnershipAccess;
  "tables/partnerships/helpers/getActiveAccommodationPartnership": typeof tables_partnerships_helpers_getActiveAccommodationPartnership;
  "tables/partnerships/helpers/getActivePartnershipsByAccommodation": typeof tables_partnerships_helpers_getActivePartnershipsByAccommodation;
  "tables/partnerships/helpers/getActivePartnershipsByHospitality": typeof tables_partnerships_helpers_getActivePartnershipsByHospitality;
  "tables/partnerships/helpers/getCustomPartnershipsForStaySafe": typeof tables_partnerships_helpers_getCustomPartnershipsForStaySafe;
  "tables/partnerships/helpers/hasActivePartnership": typeof tables_partnerships_helpers_hasActivePartnership;
  "tables/partnerships/helpers/insertPartnership": typeof tables_partnerships_helpers_insertPartnership;
  "tables/partnerships/helpers/reactivatePartnership": typeof tables_partnerships_helpers_reactivatePartnership;
  "tables/partnerships/helpers/resolveGuestPartnershipOffer": typeof tables_partnerships_helpers_resolveGuestPartnershipOffer;
  "tables/partnerships/mutations/acceptPartnershipRequest": typeof tables_partnerships_mutations_acceptPartnershipRequest;
  "tables/partnerships/mutations/createCustomPartnership": typeof tables_partnerships_mutations_createCustomPartnership;
  "tables/partnerships/mutations/createPartnership": typeof tables_partnerships_mutations_createPartnership;
  "tables/partnerships/mutations/declinePartnershipRequest": typeof tables_partnerships_mutations_declinePartnershipRequest;
  "tables/partnerships/mutations/deletePartnerships": typeof tables_partnerships_mutations_deletePartnerships;
  "tables/partnerships/mutations/revokePartnership": typeof tables_partnerships_mutations_revokePartnership;
  "tables/partnerships/mutations/updatePartnershipBenefit": typeof tables_partnerships_mutations_updatePartnershipBenefit;
  "tables/partnerships/queries/fetchAccommodationCustomPartnerships": typeof tables_partnerships_queries_fetchAccommodationCustomPartnerships;
  "tables/partnerships/queries/fetchActivePartnershipsSafe": typeof tables_partnerships_queries_fetchActivePartnershipsSafe;
  "tables/partnerships/queries/fetchAllPartnershipsAdmin": typeof tables_partnerships_queries_fetchAllPartnershipsAdmin;
  "tables/partnerships/queries/fetchStayPlatformPartnerships": typeof tables_partnerships_queries_fetchStayPlatformPartnerships;
  "tables/partnerships/schemas/partnershipsSchemas": typeof tables_partnerships_schemas_partnershipsSchemas;
  "tables/partnerships/types/partnershipsTypes": typeof tables_partnerships_types_partnershipsTypes;
  "tables/partnerships/utils/parsePartnershipBenefit": typeof tables_partnerships_utils_parsePartnershipBenefit;
  "tables/partnerships/validators/partnershipQueryValidators": typeof tables_partnerships_validators_partnershipQueryValidators;
  "tables/proTrials/crons/proTrialCron": typeof tables_proTrials_crons_proTrialCron;
  "tables/proTrials/helpers/proTrial": typeof tables_proTrials_helpers_proTrial;
  "tables/proTrials/mutations/startProTrial": typeof tables_proTrials_mutations_startProTrial;
  "tables/proTrials/registerProTrialCrons": typeof tables_proTrials_registerProTrialCrons;
  "tables/proTrials/schemas/proTrialsSchemas": typeof tables_proTrials_schemas_proTrialsSchemas;
  "tables/reports/mutations/createReport": typeof tables_reports_mutations_createReport;
  "tables/reports/queries/fetchReports": typeof tables_reports_queries_fetchReports;
  "tables/reports/schemas/reportsSchemas": typeof tables_reports_schemas_reportsSchemas;
  "tables/reservations/emails/sendReservationEmailToGuest": typeof tables_reservations_emails_sendReservationEmailToGuest;
  "tables/reservations/emails/sendReservationEmailToHospitalityOwner": typeof tables_reservations_emails_sendReservationEmailToHospitalityOwner;
  "tables/reservations/helpers/cancelPendingReservationsForGuest": typeof tables_reservations_helpers_cancelPendingReservationsForGuest;
  "tables/reservations/helpers/createFetchReservationsQuery": typeof tables_reservations_helpers_createFetchReservationsQuery;
  "tables/reservations/helpers/getGuestActiveHospitalityReservation": typeof tables_reservations_helpers_getGuestActiveHospitalityReservation;
  "tables/reservations/helpers/hospitalityHasOpenReservations": typeof tables_reservations_helpers_hospitalityHasOpenReservations;
  "tables/reservations/mutations/cancelReservation": typeof tables_reservations_mutations_cancelReservation;
  "tables/reservations/mutations/confirmReservation": typeof tables_reservations_mutations_confirmReservation;
  "tables/reservations/mutations/createReservation": typeof tables_reservations_mutations_createReservation;
  "tables/reservations/mutations/markReservationNoShow": typeof tables_reservations_mutations_markReservationNoShow;
  "tables/reservations/queries/fetchCancelledReservations": typeof tables_reservations_queries_fetchCancelledReservations;
  "tables/reservations/queries/fetchConfirmedReservations": typeof tables_reservations_queries_fetchConfirmedReservations;
  "tables/reservations/queries/fetchNoShowReservations": typeof tables_reservations_queries_fetchNoShowReservations;
  "tables/reservations/queries/fetchPendingReservations": typeof tables_reservations_queries_fetchPendingReservations;
  "tables/reservations/queries/fetchReservationsSummary": typeof tables_reservations_queries_fetchReservationsSummary;
  "tables/reservations/schemas/reservationsSchemas": typeof tables_reservations_schemas_reservationsSchemas;
  "tables/reservations/types/reservationsTypes": typeof tables_reservations_types_reservationsTypes;
  "tables/reservations/validators/reservationQueryValidators": typeof tables_reservations_validators_reservationQueryValidators;
  "tables/users/userMutations": typeof tables_users_userMutations;
  "tables/users/userQueries": typeof tables_users_userQueries;
  "types/convexTypes": typeof types_convexTypes;
  "utils/convexValidationUtils": typeof utils_convexValidationUtils;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  analytics: import("@piton-/analytics-convex/_generated/component.js").ComponentApi<"analytics">;
  rateLimiter: import("@convex-dev/rate-limiter/_generated/component.js").ComponentApi<"rateLimiter">;
  betterAuth: import("../auth/component/_generated/component.js").ComponentApi<"betterAuth">;
  r2: import("@convex-dev/r2/_generated/component.js").ComponentApi<"r2">;
  resend: import("@convex-dev/resend/_generated/component.js").ComponentApi<"resend">;
};
